apiVersion: v1
kind: Service
metadata:
  labels:
    app: dev-container
  name: dev-container
spec:
  ports:
    - name: rsync
      protocol: TCP
      port: 20873
      targetPort: 873
  selector:
    name: car
  type: LoadBalancer